name: tests-and-release

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: write

env:
  GO_VERSION: "1.24"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: unit tests
        run: go test ./...

  release:
    runs-on: ubuntu-latest
    needs: unit-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: create release
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
