name: unit-tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: unit tests
        run: go test ./...
